### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by 152haha** [liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism#1]
Hello, your code is not complete, can you reissue it, thank you, learn to refer to it。

**Comment by liguge** [comment]
We are very glad that you are following our work.
1. The most important documents have been uploaded, you can refer to our paper. 
 https://doi.org/10.1016/j.measurement.2021.110242
2. The data preprocessing part has not been uploaded yet, you can refer to this part:

 Data preprocessing in
 https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark

The resulting dataset is then fed into the model. If you have any questions, please send an email to ask specific questions.

**Comment by liguge** [comment]
- [ ] 

> We are very glad that you are following our work.
> 
> 1. The most important documents have been uploaded, you can refer to our paper.
>    https://doi.org/10.1016/j.measurement.2021.110242
> 2. The data preprocessing part has not been uploaded yet, you can refer to this part:
> 
> Data preprocessing in https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark
> 
> The resulting dataset is then fed into the model. If you have any questions, please send an email to ask specific questions.



> Hello, your code is not complete, can you reissue it, thank you, learn to refer to it。

We are very glad that you are following our work.

The most important documents have been uploaded, you can refer to our paper.
https://doi.org/10.1016/j.measurement.2021.110242
The data preprocessing part has not been uploaded yet, you can refer to this part:
Data preprocessing in
https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark

The resulting dataset is then fed into the model. If you have any questions, please send an email to ask specific questions.

**Comment by liguge** [comment]
> We are very glad that you are following our work.
> 
> 1. The most important documents have been uploaded, you can refer to our paper.
>    https://doi.org/10.1016/j.measurement.2021.110242
> 2. The data preprocessing part has not been uploaded yet, you can refer to this part:
> 
> Data preprocessing in https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark
> 
> The resulting dataset is then fed into the model. If you have any questions, please send an email to ask specific questions.

We are very glad that you are following our work.

The most important documents have been uploaded, you can refer to our paper.
https://doi.org/10.1016/j.measurement.2021.110242
The data preprocessing part has not been uploaded yet, you can refer to this part:
Data preprocessing in
https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark

The resulting dataset is then fed into the model. If you have any questions, please send an email to ask specific questions.

**Comment by liguge** [comment]
> Hello, your code is not complete, can you reissue it, thank you, learn to refer to it。

We are very glad that you are following our work.

The most important documents have been uploaded, you can refer to our paper.
https://doi.org/10.1016/j.measurement.2021.110242
The data preprocessing part has not been uploaded yet, you can refer to this part:
Data preprocessing in
https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark

The resulting dataset is then fed into the model. If you have any questions, please send an email to ask specific questions.

**Comment by sunfeng90** [comment]
Thanks for this great work and paper.

I think the ReadMe file is so simple and don't know how to run this project for a beginner.

I suggest  u can update the ReadMe.md and tell the beginner how to run this project step by step.

Thanks a lot.

**Comment by liguge** [comment]
> Thanks for this great work and paper.
> 
> I think the ReadMe file is so simple and don't know how to run this project for a beginner.
> 
> I suggest u can update the ReadMe.md and tell the beginner how to run this project step by step.
> 
> Thanks a lot.

thanks for your suggestions，I will update when I arrive at lab., tomorrow.

**Comment by sunfeng90** [comment]
Thanks a lot. I'm reading this paper which is great and detailed. I found there missing the codes about Label smoothing regularization in the project.

**Comment by liguge** [comment]
> Thanks a lot. I'm reading this paper which is great and detailed. I found there missing the codes about Label smoothing regularization in the project.

https://github.com/liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism/blob/main/label_smoothing.py   here！

**Comment by sunfeng90** [comment]
Thanks, i will check



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月21日 23:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism] thanks (Issue #1) |

Thanks a lot. I'm reading this paper which is great and detailed. I found there missing the codes about Label smoothing regularization in the project.

https://github.com/liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism/blob/main/label_smoothing.py here！

**Comment by liguge** [comment]
> Thanks a lot. I'm reading this paper which is great and detailed. I found there missing the codes about Label smoothing regularization in the project.


now pytorch has supported LSR. or    torch.nn.CrossEntropyLoss(label_smoothing=0.1)

**Comment by liguge** [comment]
> Thanks, i will check
> […](#)
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2022年04月21日 23:26 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.******@***.***> |
> | 主题 | Re: [liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism] thanks (Issue #1) |
> 
> Thanks a lot. I'm reading this paper which is great and detailed. I found there missing the codes about Label smoothing regularization in the project.
> 
> https://github.com/liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism/blob/main/label_smoothing.py here！
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

or pip install timm,  timm(api) is also supported LSR.

**Comment by sunfeng90** [comment]
Okay.thanks a lot. Good night, Sir.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月21日 23:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism] thanks (Issue #1) |

Thanks a lot. I'm reading this paper which is great and detailed. I found there missing the codes about Label smoothing regularization in the project.
now pytorch has supported LSR. or torch.nn.CrossEntropyLoss(label_smoothing=0.1)

**Comment by sunfeng90** [comment]
I found there are label_smoothing now. Thanks a lot.

But there are no datasave which remind errors in model_train.py.

**Comment by liguge** [comment]
> 

https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark/blob/master/CNN_Datasets/O_A/datasets/CWRU.py

https://github.com/liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism/blob/main/datasave.py

https://github.com/Xiaohan-Chen/baer_fault_diagnosis/blob/master/cnn_lstm_model.ipynb

You can refer to the code to build your own dataset, here.

**Comment by liguge** [comment]
> I found there are label_smoothing now. Thanks a lot.
> 
> But there are no datasave which remind errors in model_train.py.

https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark/blob/master/CNN_Datasets/O_A/datasets/CWRU.py

https://github.com/liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism/blob/main/datasave.py

https://github.com/Xiaohan-Chen/baer_fault_diagnosis/blob/master/cnn_lstm_model.ipynb

You can refer to the code to build your own dataset, here.

**Comment by sunfeng90** [comment]
Okay.Thanks a lot.


On 4/22/2022 ***@***.***> wrote：

I found there are label_smoothing now. Thanks a lot.

But there are no datasave which remind errors in model_train.py.

https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark/blob/master/CNN_Datasets/O_A/datasets/CWRU.py

https://github.com/liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism/blob/main/datasave.py

https://github.com/Xiaohan-Chen/baer_fault_diagnosis/blob/master/cnn_lstm_model.ipynb

You can refer to the code to build your own dataset, here.

**Comment by sunfeng90** [comment]
Thanks for your timely reply.

I will try and I will consult u when I face new problems.

**Comment by liguge** [comment]
> Thanks for your timely reply.
> 
> I will try and I will consult u when I face new problems.

OK, NO problems.

**Comment by 152haha** [comment]
Hello, I have a problem running the code, I don't know how to solve it, can you give some advice？
 PermissionError: [Errno 13] Permission denied: 'B0503_LSTM.pt'

**Comment by liguge** [comment]
I'm glad you pay attention to our work. This line is to load the pre-training model. You can comment out this sentence directly, which will not affect the training of the model.

在 2022-05-01 15:46:48，152haha ***@***.***> 写道：


Hello, I have a problem running the code, I don't know how to solve it, can you give some advice？
PermissionError: [Errno 13] Permission denied: 'B0503_LSTM.pt'
