### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by BALDman66** [liguge/Fault-diagnosis-for-small-samples-based-on-attention-mechanism#3]
您好如果我想训练完进行测试是否需要自行写测试文件代码？

**Comment by liguge** [comment]
Yes, the test set has the same files as the validation set, but the data set is loaded differently.

**Comment by liguge** [comment]
> 您好如果我想训练完进行测试是否需要自行写测试文件代码？
Yes, the test set has the same files as the validation set, but the data set is loaded differently.
